# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.roll_any <- function(x, width, min_obs, complete_obs, na_restore, online) {
    .Call(`_roll_roll_any`, x, width, min_obs, complete_obs, na_restore, online)
}

.roll_all <- function(x, width, min_obs, complete_obs, na_restore, online) {
    .Call(`_roll_roll_all`, x, width, min_obs, complete_obs, na_restore, online)
}

.roll_sum <- function(x, width, weights, min_obs, complete_obs, na_restore, online) {
    .Call(`_roll_roll_sum`, x, width, weights, min_obs, complete_obs, na_restore, online)
}

.roll_prod <- function(x, width, weights, min_obs, complete_obs, na_restore, online) {
    .Call(`_roll_roll_prod`, x, width, weights, min_obs, complete_obs, na_restore, online)
}

.roll_mean <- function(x, width, weights, min_obs, complete_obs, na_restore, online) {
    .Call(`_roll_roll_mean`, x, width, weights, min_obs, complete_obs, na_restore, online)
}

.roll_idxquantile <- function(x, width, weights, p, min_obs, complete_obs, na_restore, online) {
    .Call(`_roll_roll_idxquantile`, x, width, weights, p, min_obs, complete_obs, na_restore, online)
}

.roll_quantile <- function(x, width, weights, p, min_obs, complete_obs, na_restore, online) {
    .Call(`_roll_roll_quantile`, x, width, weights, p, min_obs, complete_obs, na_restore, online)
}

.roll_var <- function(x, width, weights, center, min_obs, complete_obs, na_restore, online) {
    .Call(`_roll_roll_var`, x, width, weights, center, min_obs, complete_obs, na_restore, online)
}

.roll_sd <- function(x, width, weights, center, min_obs, complete_obs, na_restore, online) {
    .Call(`_roll_roll_sd`, x, width, weights, center, min_obs, complete_obs, na_restore, online)
}

.roll_scale <- function(x, width, weights, center, scale, min_obs, complete_obs, na_restore, online) {
    .Call(`_roll_roll_scale`, x, width, weights, center, scale, min_obs, complete_obs, na_restore, online)
}

.roll_cov <- function(x, y, width, weights, center, scale, min_obs, complete_obs, na_restore, online) {
    .Call(`_roll_roll_cov`, x, y, width, weights, center, scale, min_obs, complete_obs, na_restore, online)
}

.roll_lm <- function(x, y, width, weights, intercept, min_obs, complete_obs, na_restore, online) {
    .Call(`_roll_roll_lm`, x, y, width, weights, intercept, min_obs, complete_obs, na_restore, online)
}

