# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

roll_mean <- function(data, width, weights, min_obs, complete_obs, na_restore, parallel_for) {
    .Call('roll_roll_mean', PACKAGE = 'roll', data, width, weights, min_obs, complete_obs, na_restore, parallel_for)
}

roll_var <- function(data, width, weights, center, min_obs, complete_obs, na_restore, parallel_for) {
    .Call('roll_roll_var', PACKAGE = 'roll', data, width, weights, center, min_obs, complete_obs, na_restore, parallel_for)
}

roll_sd <- function(data, width, weights, center, min_obs, complete_obs, na_restore, parallel_for) {
    .Call('roll_roll_sd', PACKAGE = 'roll', data, width, weights, center, min_obs, complete_obs, na_restore, parallel_for)
}

roll_scale <- function(data, width, weights, center, scale, min_obs, complete_obs, na_restore, parallel_for) {
    .Call('roll_roll_scale', PACKAGE = 'roll', data, width, weights, center, scale, min_obs, complete_obs, na_restore, parallel_for)
}

roll_cov <- function(data, width, weights, center, scale, min_obs, complete_obs, na_restore, parallel_for) {
    .Call('roll_roll_cov', PACKAGE = 'roll', data, width, weights, center, scale, min_obs, complete_obs, na_restore, parallel_for)
}

roll_lm <- function(x, y, width, weights, center_x, center_y, scale_x, scale_y, min_obs, complete_obs, na_restore, parallel_for) {
    .Call('roll_roll_lm', PACKAGE = 'roll', x, y, width, weights, center_x, center_y, scale_x, scale_y, min_obs, complete_obs, na_restore, parallel_for)
}

roll_eigen <- function(data, width, weights, center, scale, min_obs, complete_obs, na_restore, parallel_for) {
    .Call('roll_roll_eigen', PACKAGE = 'roll', data, width, weights, center, scale, min_obs, complete_obs, na_restore, parallel_for)
}

roll_pcr <- function(x, y, width, comps, weights, center_x, center_y, scale_x, scale_y, min_obs, complete_obs, na_restore, parallel_for) {
    .Call('roll_roll_pcr', PACKAGE = 'roll', x, y, width, comps, weights, center_x, center_y, scale_x, scale_y, min_obs, complete_obs, na_restore, parallel_for)
}

roll_vif <- function(data, width, comps, weights, center, scale, min_obs, complete_obs, na_restore, parallel_for) {
    .Call('roll_roll_vif', PACKAGE = 'roll', data, width, comps, weights, center, scale, min_obs, complete_obs, na_restore, parallel_for)
}

